--- #YAML:1.0
name:               Feersum
version:            1.201
abstract:           A PSGI engine for Perl based on EV/libev
author:
    - Jeremy Stashewsky <stash@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    EV:                   4
    ExtUtils::MakeMaker:  6.51
build_requires:
    AnyEvent:     5.261
    Guard:        1.012
    Test::Fatal:  0.003
    Test::More:   0.94
requires:
    EV:            4
    Scalar::Util:  1.19
resources:
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/stash/Feersum.git
no_index:
    directory:
        - t
        - inc
        - eg
        - picohttpparser-git
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    JSON::XS:         2
    Plack:            0.995
    Test::LeakTrace:  0.13
    Test::TCP:        1.12
