--- #YAML:1.0
name:               Feersum
version:            0.97
abstract:           A scary-fast HTTP engine for Perl based on EV/libev
author:
    - Jeremy Stashewsky <stash@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    EV:                   3.9
    ExtUtils::MakeMaker:  6.51
build_requires:
    AnyEvent:         5.261
    Guard:            1.012
    Scalar::Util:     1.19
    Test::Exception:  0.29
    Test::More:       0.94
requires:
    EV:  3.9
resources:
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/stash/Feersum.git
no_index:
    directory:
        - t
        - inc
        - eg
        - picohttpparser-git
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Plack:      0.995
    Test::TCP:  0.16
