---
abstract: 'A PSGI engine for Perl based on EV/libev'
author:
  - 'Jeremy Stashewsky <stash@cpan.org>'
build_requires:
  AnyEvent: 5.261
  Guard: 1.012
  Test::Fatal: 0.003
  Test::More: 0.94
  Test::TCP: 1.12
configure_requires:
  EV: 4
  ExtUtils::MakeMaker: 6.51
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Feersum
no_index:
  directory:
    - t
    - inc
    - eg
    - picohttpparser-git
recommends:
  Test::LeakTrace: 0.13
requires:
  EV: 4
  JSON::XS: 2
  Plack: 0.995
  Scalar::Util: 1.19
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/stash/Feersum.git
version: 1.401
